# Generated by Django 3.2 on 2021-04-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth2_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='oauth2_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
