# Generated by Django 3.2 on 2021-05-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210422_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='oauth2_id',
            new_name='oauth2_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth2_key',
        ),
    ]
