# Generated by Django 3.2 on 2021-05-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210510_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='polar_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
