# Generated by Django 3.2 on 2021-05-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210511_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
