# Generated by Django 3.2 on 2021-05-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth2_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subject_id',
        ),
    ]
