# Generated by Django 3.2 on 2021-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210609_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name='privacy'),
        ),
    ]
