# Generated by Django 3.2 on 2021-06-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Consented to study'),
        ),
        migrations.AlterField(
            model_name='user',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name='Agreed to privacy notice'),
        ),
    ]
