# Generated by Django 3.2 on 2021-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210610_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1, max_length=32, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
