# Generated by Django 3.2 on 2021-06-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_survey_done',
            field=models.BooleanField(default=False, verbose_name='Filled first survey'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ID'),
        ),
    ]
