# Generated by Django 3.2 on 2021-06-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210615_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorized',
            field=models.BooleanField(default=False, verbose_name='Authorized access'),
        ),
    ]
