# Generated by Django 3.2 on 2021-06-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_authorized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.CharField(blank=True, help_text="<ul><li>Address for sending the Polar fitness tracker. It can be any address within Finland where you would like to receive the fitness tracker. (Don't fill if you already have one.)</li></ul>", max_length=50, verbose_name='home address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_own_device',
            field=models.BooleanField(default=False, help_text="<ul><li>Check this if you <b>don't</b> want us to send you a device.</li></ul>", verbose_name='I already have a Polar fitness tracker'),
        ),
    ]
