# Generated by Django 3.2 on 2021-06-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S: 130–185 mm'), ('M/L', 'M/L: 155–210 mm')], help_text='<ul><li>Size of the fitness tracker we send you.</li></ul>', max_length=20, verbose_name='Fitness tracker size'),
        ),
    ]
