# Generated by Django 3.2 on 2021-06-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='has_received_email',
            field=models.BooleanField(default=False, verbose_name='Has received email'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S: wrist circumference 130–185 mm'), ('M/L', 'M/L: wrist circumference 155–210 mm')], help_text='<ul><li>Size of the fitness tracker we send you.</li></ul>', max_length=20, verbose_name='Fitness tracker size'),
        ),
    ]
