# Generated by Django 3.2 on 2021-06-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_has_received_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_sent',
            field=models.BooleanField(default=False, verbose_name='Fitness tracker sent'),
        ),
    ]
