# Generated by Django 3.2 on 2021-06-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_received_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='received_data',
        ),
    ]
