# Generated by Django 3.2 on 2021-06-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_user_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_own_device',
            field=models.BooleanField(default=False, help_text='<ul><li>We have run out of fitness trackers, please only register if you have a Polar fitness tracker of your own.</li></ul>', verbose_name='I already have a Polar fitness tracker'),
        ),
    ]
