# Generated by Django 3.2 on 2021-08-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20210812_1351'),
        ('users', '0033_alter_user_received_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filled_surveys',
            field=models.ManyToManyField(to='survey.Survey'),
        ),
    ]
