# Generated by Django 3.2 on 2021-08-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_filled_surveys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dropped_out',
            field=models.BooleanField(default=False, verbose_name='Dropped out'),
        ),
    ]
