# Generated by Django 3.2 on 2021-08-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20210812_1407'),
        ('users', '0035_user_dropped_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='filled_surveys',
            field=models.ManyToManyField(blank=True, to='survey.Survey'),
        ),
    ]
