# Generated by Django 3.2 on 2021-09-03 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_user_date_received_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_received_date',
            new_name='data_received_date',
        ),
    ]
